# This file should be moved to .github/workflows/ci.yml
# The OAuth token doesn't have workflow permissions, so this needs to be added manually

name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test Scripts
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y bc maven shellcheck
        
    - name: Make scripts executable
      run: chmod +x scripts/*.sh tests/*.sh
      
    - name: Lint shell scripts
      run: |
        find scripts/ -name "*.sh" -exec shellcheck {} \;
        find tests/ -name "*.sh" -exec shellcheck {} \;
        
    - name: Run tests
      run: ./tests/test-benchmark.sh
      
    - name: Test environment check
      run: ./scripts/run-benchmark.sh --check
      
    - name: Test project generation
      run: ./scripts/create-test-project.sh

  benchmark:
    name: Quick Benchmark
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y bc maven
        
    - name: Download Maven 4.0.0-rc-4
      run: |
        wget -q https://archive.apache.org/dist/maven/maven-4/4.0.0-rc-4/binaries/apache-maven-4.0.0-rc-4-bin.tar.gz
        sudo tar -xzf apache-maven-4.0.0-rc-4-bin.tar.gz -C /opt/
        sudo ln -sf /opt/apache-maven-4.0.0-rc-4 /opt/maven
        
    - name: Make scripts executable
      run: chmod +x scripts/*.sh
      
    - name: Update configuration for CI
      run: |
        sed -i 's|export MAVEN4_RC4_PATH=.*|export MAVEN4_RC4_PATH="/opt/maven/bin/mvn"|' scripts/benchmark-config.sh
        sed -i 's|export MAVEN4_CURRENT_PATH=.*|export MAVEN4_CURRENT_PATH="/usr/bin/mvn"|' scripts/benchmark-config.sh
        
    - name: Run quick benchmark
      run: |
        timeout 600 ./scripts/run-benchmark.sh --quick || true
        
    - name: Upload results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: benchmark-results
        path: |
          results/
          maven-benchmark/
        retention-days: 30

  documentation:
    name: Check Documentation
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install markdown tools
      run: |
        npm install -g markdownlint-cli
        
    - name: Lint markdown
      run: |
        markdownlint README.md docs/*.md
        
    - name: Check for broken links
      uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        use-quiet-mode: 'yes'
        use-verbose-mode: 'yes'
